service: express-dynamodb-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2

functions:
  app:
    handler: lambda.handler
    events:
      - httpApi:
          path: /
          method: ANY
          cors: true
      - httpApi:
          path: /{proxy+}
          method: ANY
          cors: true 
      - httpApi:
          path: /users
          method: get
          cors: true 

plugins:
  - serverless-offline
